2022-01-05 20:16:51   Arguments: Namespace(use_netvlad=None, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=50, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='Data/', exp_name='default', output_folder='runs/default/2022-01-05_20-16-51')
2022-01-05 20:16:51   The outputs are being saved in runs/default/2022-01-05_20-16-51
2022-01-05 20:16:51   Using 1 GPUs and 12 CPUs
2022-01-05 20:16:51   Loading dataset Pitts30k from folder Data/
2022-01-05 20:16:51   There are 96 queries without any positives within the training set. They won't be considered as they're useless for training.
2022-01-05 20:16:51   Train query set: < TripletsDataset, pitts30k - #database: 10000; #queries: 7320 >
2022-01-05 20:16:51   Val set: < BaseDataset, pitts30k - #database: 10000; #queries: 7608 >
2022-01-05 20:16:52   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2022-01-05 20:16:53   Train only conv4 of the ResNet-18 (remove conv5), freeze the previous ones
2022-01-05 20:16:55   Output dimension of the model is 256
2022-01-05 20:16:55   Start training epoch: 00
2022-01-05 20:16:55   Cache: 0 / 5
2022-01-05 20:16:56   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/train.py", line 70, in <module>
    triplets_ds.compute_triplets(args, model)
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 206, in compute_triplets
    cache = self.compute_cache(args, model, subset_ds, (len(self), args.features_dim))
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 166, in compute_cache
    features = model(images)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/franzhd/Aml_project/project_vg/network.py", line 26, in forward
    x = self.backbone(x)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 1297, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

