2022-01-20 11:48:23   Arguments: Namespace(upscale_input=False, downscale_input=False, augment_input='None', backbone='resnet18', use_netvlad=True, netvlad_clusters=64, use_gem=None, gem_p=3, gem_eps=1e-06, use_attention='cbam', attention_lr=0.001, use_sgd=None, use_adagrad=None, momentum=0.9, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=5, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cpu', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='Dataset_pitts30k', exp_name='default', test_dataset_name='pitts30k', test_model_path='./runs/default/2022-01-20_04-39-02/best_model.pth', save_attention_mask=True, output_folder='test_runs/default/2022-01-20_11-48-23')
2022-01-20 11:48:23   The outputs are being saved in test_runs/default/2022-01-20_11-48-23
2022-01-20 11:48:24   Using 1 GPUs and 12 CPUs
2022-01-20 11:48:24   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2022-01-20 11:51:52   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/run_test.py", line 46, in <module>
    recalls, recalls_str = test.test(args, test_ds, model)
  File "/home/franzhd/Aml_project/project_vg/test.py", line 29, in test
    save_attention_mask(
  File "/home/franzhd/Aml_project/project_vg/util.py", line 43, in save_attention_mask
    plt.show()
  File "/home/franzhd/.local/lib/python3.9/site-packages/matplotlib/pyplot.py", line 368, in show
    return _backend_mod.show(*args, **kwargs)
  File "/home/franzhd/.local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3544, in show
    cls.mainloop()
  File "/home/franzhd/.local/lib/python3.9/site-packages/matplotlib/backends/_backend_gtk.py", line 171, in mainloop
    _application.run()  # Quits when all added windows close.
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

